version: '3.8'


services:
  app:
    build: .
    container_name: import_service
    volumes:
      - .:/app
      - logs:/app/logs
    command: ["python", "main.py", "--run-mode", "continuous"]
    network_mode: "host"

volumes:
  logs: