name: Build and Push Docker Image For Data Sync Microservice

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./data_sync_microservice  # Adjust the context to the subdirectory
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/OpenLMIS-data_sync_microservice:latest
          tags: ghcr.io/${{ github.repository_owner }}/sigeca-synchronization:${{ github.ref_name }}  # Tag with the branch name

      - name: Log out of GitHub Container Registry
        run: docker logout ghcr.io
