name: Build and Push Docker Image For Sigeca Data Export Microservice

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./sigeca_data_export_microservice  # Adjust the context to the subdirectory
          push: true
          tags: |
            ghcr.io/openlmis-angola/open-lmis-sigeca-data-export-microservice:latest
            ghcr.io/openlmis-angola/open-lmis-sigeca-data-export-microservice:${{ github.ref_name }}

      - name: Log out of GitHub Container Registry
        run: docker logout ghcr.io

  build-import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./sigeca_data_import_microservice  # Adjust the context to the subdirectory
          push: true
          tags: |
            ghcr.io/openlmis-angola/open-lmis-sigeca-data-import-microservice:latest
            ghcr.io/openlmis-angola/open-lmis-sigeca-data-export-microservice:${{ github.ref_name }}

      - name: Log out of GitHub Container Registry
        run: docker logout ghcr.io
